### ISSUE TITLE
Presentation file?

### ISSUE THREAD

**Issue by donbowen** [LeDataSciFi/the-fin388-project-hacking-coursesite#2]
@rev222 Please upload the presentation file here :)

(Or attach a link to the google slides if that's what you did)

**Comment by rev222** [comment]
[Predicting and Comparing Future Growth.pdf](https://github.com/LeDataSciFi/the-fin388-project-hacking-coursesite/files/6495329/Predicting.and.Comparing.Future.Growth.pdf)

**Comment by donbowen** [comment]
That's the PDF of a google slides, right? (I'll upload it into the repo)

**Comment by donbowen** [comment]
Thanks!

**Comment by donbowen** [comment]
Thanks!

**Comment by rev222** [comment]
Yes it is! I apologize, someone in our group was supposed to upload it and
may have forgotten.

**Comment by donbowen** [comment]
No worries
